# 데이터 가져오기

In [2]:
import pandas as pd
df = pd.read_csv('C:/ai_x/download/shareData/부동산_250213/최종전국평당분양가격(결측치제외).csv',
                 encoding='cp949')
df.head()

지역명    연도   월   평당분양가격
0  서울  2013  12  18189.0
1  부산  2013  12   8111.0
2  대구  2013  12   8080.0
3  인천  2013  12  10204.0
4  광주  2013  12   6098.0

In [ ]:
# 집버전
import pandas as pd
df = pd.read_csv('C:/ai_x/download/shareData/부동산_250213/최종전국평당분양가격(결측치제외).csv',
                 encoding='cp949')
df.head()

# 2. 지역명의 라벨 인코딩
- 지역명을 라벨인코딩한 지역명2
- 분석할 경우 원핫인코딩까지 할 것을 추천

In [5]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

data = np.array(['red', 'green', 'blue', 'green', 'red']).reshape(-1, 1)
encoder = OneHotEncoder(sparse=False)
onehot = encoder.fit_transform(data)
print(onehot)


[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


c:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


# 3. normalization 스케일 조정
- 입력변수(지역명2, 연도, 월)와 타겟변수(평당분양가격) 따로 스케일 조정(MinMaxScaler 이용)
- 지역명2n, 연도n, 월n필드 추가

# 4. standarization 스케일 조정
- 입력변수와 타겟변수 따로 스케일 조정(StandardScaler이용)
- 지역명2s, 연도s, 월s필드 추가